In [1]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [2]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez('one_array',array1,array2)

In [37]:
#2. 讀取剛剛的npz檔
one=np.load('one_array.npz')
print(".npz檔案:\n",one.files,"\narray1:\n",one['arr_0'],"\narray2:\n",one['arr_1'])

.npz檔案:
 ['arr_0', 'arr_1'] 
array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 
array2:
 [2 3 5]


In [36]:
#3.加入下列array3一起存成新的npz檔
array3 = np.arange(40).reshape((5, 8),order='F')
np.savez('two_array',array1,array2,array3)
two=np.load('two_array.npz')
print("array1:\n",two['arr_0'],"\narray2:\n",two['arr_1'],"\narray3:\n",two['arr_2'])

array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 
array2:
 [2 3 5] 
array3:
 [[ 0  5 10 15 20 25 30 35]
 [ 1  6 11 16 21 26 31 36]
 [ 2  7 12 17 22 27 32 37]
 [ 3  8 13 18 23 28 33 38]
 [ 4  9 14 19 24 29 34 39]]
